num1 = int(input("Enter 1st number:"))
num2 = int(input("Enter 2nd number:"))
num3 = int(input("Enter 3rd number:"))
num4 = int(input("Enter 4th number:"))
num5 = int(input("Enter 5th number:"))
num6 = int(input("Enter 6th number:"))
num7 = int(input("Enter 7th number:"))
num8 = int(input("Enter 8th number:"))
total = {num1,num2,num3,num4,num5,num6,num7,num8}
print(total) 